// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainFrontLeft = NULL;
SpeedController* RobotMap::driveTrainFrontRight = NULL;
SpeedController* RobotMap::driveTrainRearLeft = NULL;
SpeedController* RobotMap::driveTrainRearRight = NULL;
RobotDrive* RobotMap::driveTrainTankDrive = NULL;
Gyro* RobotMap::driveTrainGyro1 = NULL;
SpeedController* RobotMap::driveTrainHLeft = NULL;
SpeedController* RobotMap::driveTrainHRight = NULL;
Encoder* RobotMap::driveTrainLeft = NULL;
Encoder* RobotMap::driveTrainRight = NULL;
Encoder* RobotMap::driveTrainMIddle = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainFrontLeft = new Talon(0);
	lw->AddActuator("DriveTrain", "Front Left", (Talon*) driveTrainFrontLeft);
	
	driveTrainFrontRight = new Talon(1);
	lw->AddActuator("DriveTrain", "Front Right", (Talon*) driveTrainFrontRight);
	
	driveTrainRearLeft = new Talon(2);
	lw->AddActuator("DriveTrain", "Rear Left", (Talon*) driveTrainRearLeft);
	
	driveTrainRearRight = new Talon(3);
	lw->AddActuator("DriveTrain", "Rear Right", (Talon*) driveTrainRearRight);
	
	driveTrainTankDrive = new RobotDrive(driveTrainFrontLeft, driveTrainRearLeft,
              driveTrainFrontRight, driveTrainRearRight);
	
	driveTrainTankDrive->SetSafetyEnabled(true);
        driveTrainTankDrive->SetExpiration(0.1);
        driveTrainTankDrive->SetSensitivity(0.5);
        driveTrainTankDrive->SetMaxOutput(1.0);

	driveTrainGyro1 = new Gyro(0);
	lw->AddSensor("DriveTrain", "Gyro 1", driveTrainGyro1);
	driveTrainGyro1->SetSensitivity(0.007);
	driveTrainHLeft = new Talon(4);
	lw->AddActuator("DriveTrain", "HLeft", (Talon*) driveTrainHLeft);
	
	driveTrainHRight = new Talon(5);
	lw->AddActuator("DriveTrain", "HRight", (Talon*) driveTrainHRight);
	
	driveTrainLeft = new Encoder(0, 1, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "Left", driveTrainLeft);
	driveTrainLeft->SetDistancePerPulse(1.0);
        driveTrainLeft->SetPIDSourceParameter(Encoder::kRate);
	driveTrainRight = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "Right", driveTrainRight);
	driveTrainRight->SetDistancePerPulse(1.0);
        driveTrainRight->SetPIDSourceParameter(Encoder::kRate);
	driveTrainMIddle = new Encoder(4, 5, false, Encoder::k4X);
	lw->AddSensor("DriveTrain", "MIddle", driveTrainMIddle);
	driveTrainMIddle->SetDistancePerPulse(1.0);
        driveTrainMIddle->SetPIDSourceParameter(Encoder::kRate);

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
